# Mapping chuẩn từ tên tiếng Việt sang key subcategory
SUBCATEGORY_MAP = {
    "Máy massage": "may-massage",
    "Kem hỗ trợ giảm mụn, gel hỗ trợ giảm mụn": "kem-ho-tro-giam-mun",
    "Dầu gội giúp giảm nấm và ngứa da đầu": "dau-goi-giam-nam",
    "Gel bôi trơn": "gel-boi-tron",
    "Sữa rửa mặt (Kem, gel, sữa)": "sua-rua-mat",
    "Nước tẩy trang, dầu tẩy trang": "nuoc-tay-trang",
    "Mặt nạ": "mat-na",
    "Dưỡng da mặt": "duong-da-mat",
    "Chăm sóc da mặt": "cham-soc-da-mat",
    "Hỗ trợ mờ sẹo, mờ vết thâm": "ho-tro-mo-seo",
    "Da mẫn cảm, dễ kích ứng": "da-man-cam",
    "Dưỡng da bị khô, thiếu ẩm": "duong-da-kho",
    "Kim các loại": "kim-cac-loai",
    "Vitamin tổng hợp": "vitamin-tong-hop",
    "Bổ sung Canxi & Vitamin D": "canxi-vitamin-d",
    "Vitamin & Khoáng chất": "vitamin-khoang-chat",
    "Bổ sung Sắt & Axit Folic": "sat-axit-folic",
    "Cơ xương khớp": "co-xuong-khop",
    "Hô hấp, ho, xoang": "ho-hap-ho-xoang",
    "Hỗ trợ điều trị trĩ": "ho-tro-dieu-tri-tri",
    "Thận, tiền liệt tuyến": "than-tien-liet-tuyen",
    "Hỗ trợ điều trị": "ho-tro-dieu-tri",
    "Bổ não - cải thiện trí nhớ": "tang-tri-nho",
    "Chăm sóc chuyên sâu cho tóc": "cham-soc-chuyen-sau-toc",
    "Túi chườm": "tui-chuom",
    "Hoạt huyết": "hoat-huyet",
    "Máy đo SpO2": "may-do-spo2",
    "Thực phẩm - Đồ uống": "thuc-pham-do-uong",
    "Nước Yến": "nuoc-yen",
    "Trà thảo dược": "tra-thao-duoc",
    "Nước uống không gas": "nuoc-uong-khong-gas",
    "Bổ mắt, bảo vệ mắt": "bo-mat",
    "Băng vệ sinh": "bang-ve-sinh",
    "Kẹo cứng": "keo-cung",
    "Dầu cá, Omega 3, DHA": "omega-3-dha",
    "Vitamin C các loại": "vitamin-c",
    "Dụng cụ tẩy lông": "dung-cu-tay-long",
    "Nước súc miệng": "nuoc-suc-mieng",
    "Kit Test Covid": "kit-test-covid",
    "Hỗ trợ mãn kinh": "ho-tro-man-kinh",
    "Hỗ trợ cải thiện quầng thâm, bọng mắt": "ho-tro-quang-tham-mat",
    "Hỗ trợ giấc ngủ ngon": "ho-tro-giac-ngu",
    "Khẩu trang vải": "khau-trang-vai",
    "Sức khoẻ tình dục": "suc-khoe-tinh-duc",
    "Khẩu trang y tế": "khau-trang-y-te",
    "Đại tràng": "dai-trang",
    "Chăm sóc da nứt nẻ": "cham-soc-da-nut-ne",
    "Hỗ trợ trao đổi chất": "ho-tro-trao-doi-chat",
    "Khăn giấy, khăn ướt": "khan-giay",
    "Máy, que thử đường huyết": "may-que-thu-duong-huyet",
    "Dưỡng tóc, ủ tóc": "duong-toc-u-toc",
    "Serum, Essence hoặc Ampoule": "serum-essence",
    "Tóc": "toc",
    "Thử thai": "que-thu-thai",
    "Dụng cụ vệ sinh mũi": "dung-cu-ve-sinh-mui",
    "Giải rượu, cai rượu": "giai-ruou",
    "Thuốc tăng cường tuần hoàn não": "tang-cuong-tuan-hoan-nao",
    "Thuốc trị trĩ, suy giãn tĩnh mạch": "thuoc-tri-tri",
    "Hỗ trợ điều trị gout": "ho-tro-dieu-tri-gout",
    "Chỉ nha khoa": "chi-nha-khoa",
    "Dung dịch vệ sinh phụ nữ": "dung-dich-ve-sinh-phu-nu",
    "Đồ dùng cho bé": "do-dung-cho-be",
    "Hỗ trợ cải thiện nếp nhăn vùng mắt": "ho-tro-nep-nhan-mat",
    "Tăng sức đề kháng, miễn dịch": "tang-suc-de-khang",
    "Đồ dùng cho mẹ": "do-dung-cho-me",
    "Trang điểm mặt": "trang-diem-mat",
    "Miếng dán giảm đau, hạ sốt": "mieng-dan-giam-dau",
    "Băng y tế": "bang-y-te",
    "Bông y tế": "bong-y-te",
    "Chống nắng toàn thân": "chong-nang-toan-than",
    "Kem chống nắng da mặt": "kem-chong-nang-da-mat",
    "Tinh dầu xông": "tinh-dau-xong",
    "Sữa": "sua",
    "Chống muỗi & côn trùng": "chong-muoi-con-trung",
    "Cồn, nước sát trùng, nước muối": "nuoc-sat-trung",
    "Vệ sinh tai": "ve-sinh-tai",
    "Dụng cụ cạo râu": "dung-cu-cao-rau",
    "Dụng cụ y tế": "dung-cu-y-te",
    "Các dụng cụ và sản phẩm khác": "dung-cu-san-pham-khac",
    "Thuốc kháng virus": "thuoc-khang-virus",
    "Thuốc trị giun sán": "thuoc-tri-giun-san",
    "Thuốc kháng sinh, kháng nấm": "thuoc-khang-sinh-khang-nam",
    "Thuốc kháng nấm": "thuoc-khang-nam",
    "Chăm sóc vết thương": "cham-soc-vet-thuong",
    "Giảm Cholesterol": "giam-cholesterol",
    "Chăm sóc răng": "cham-soc-rang",
    "Cân bằng nội tiết tố": "can-bang-noi-tiet-to",
    "Tinh dầu trị cảm": "tinh-dau-tri-cam",
    "Tinh dầu massage": "tinh-dau-massage",
    "Khó tiêu": "kho-tieu",
    "Sữa dưỡng thể, kem dưỡng thể": "sua-duong-the",
    "Sữa tắm, xà bông": "sua-tam-xa-bong",
    "Kem đánh răng": "kem-danh-rang",
    "Bao cao su": "bao-cao-su",
    "Kem hỗ trợ mờ nám, tàn nhang, đốm nâu": "kem-mo-nam-tan-nhang",
    "Táo bón": "tao-bon",
    "Tinh dầu": "tinh-dau",
    "Suy giãn tĩnh mạch": "suy-gian-tinh-mach",
    "Kiểm soát căng thẳng": "kiem-soat-cang-thang",
    "Dưỡng da mắt": "duong-da-mat",
    "Chức năng gan": "chuc-nang-gan",
    "Sinh lý nữ": "sinh-ly-nu",
    "Da": "da",
    "Vớ ngăn tĩnh mạch": "vo-ngan-tinh-mach",
    "Đường ăn kiêng": "duong-an-kieng",
    "Son môi": "son-moi",
    "Dầu gội dầu xả": "dau-goi-dau-xa",
    "Vi sinh - Probiotic": "vi-sinh-probiotic",
    "Huyết áp": "huyet-ap",
    "Thuốc thần kinh": "thuoc-than-kinh",
    "Máy đo huyết áp": "may-do-huyet-ap",
    "Chăm sóc cơ thể": "cham-soc-co-the",
    "Lăn khử mùi, xịt khử mùi": "lan-xit-khu-mui",
    "Kem dưỡng da tay, chân": "kem-duong-tay-chan",
    "Chống lão hóa": "chong-lao-hoa",
    "Bàn chải điện": "ban-chai-dien",
    "Xịt giảm đau, kháng viêm": "xit-giam-dau",
    "Thuốc dạ dày": "thuoc-da-day",
    "Thuốc tiêu hoá": "thuoc-tieu-hoa",
    "Thuốc trị bệnh gan": "thuoc-tri-benh-gan",
    "Thuốc trị tiêu chảy": "thuoc-tri-tieu-chay",
    "Thuốc trị táo bón": "thuoc-tri-tao-bon",
    "Dạ dày, tá tràng": "da-day-ta-trang",
    "Sinh lý nam": "sinh-ly-nam",
    "Tuần hoàn máu": "tuan-hoan-mau",
    "Nước rửa tay": "nuoc-rua-tay",
    "Nhiệt kế": "nhiet-ke"
}
